# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Hello CDP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hello CDP
  pod 'MarketingCloud-Cdp', '~> 2.0.4'

end