source 'https://cdn.cocoapods.org/'
# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Hello CDP (Pods)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hello CDP
  pod 'MarketingCloud-Cdp', '~> 3.0'
end