# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Hello CDP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hello CDP
  pod 'MarketingCloud-Cdp', '~> 1.0'

end
